In [7]:
import pandas as pd
from pathlib import Path

In [8]:
CACHE_DIR = Path("JWST_NIRCam_Triple_Filter") / "cache"

In [9]:
df_F200 = pd.read_parquet(CACHE_DIR / "F200W_products.parquet")
df_F277 = pd.read_parquet(CACHE_DIR / "F277W_products.parquet")
df_F444 = pd.read_parquet(CACHE_DIR / "F444W_products.parquet")

In [10]:
print(df_F200.columns.tolist())

['obsID', 'obs_collection', 'dataproduct_type', 'obs_id', 'description', 'type', 'dataURI', 'productType', 'productGroupDescription', 'productSubGroupDescription', 'productDocumentationURL', 'project', 'prvversion', 'proposal_id', 'productFilename', 'size', 'parent_obsid', 'dataRights', 'calib_level', 'filters', 's_ra', 's_dec']

In [11]:
df_F200.head(10)

,obsID,obs_collection,dataproduct_type,obs_id,description,type,dataURI,productType,productGroupDescription,productSubGroupDescription,...,prvversion,proposal_id,productFilename,size,parent_obsid,dataRights,calib_level,filters,s_ra,s_dec
0,71774283,JWST,image,jw01410-o057_t051_nircam_clear-f200w,target (L3) : segmentation map,D,mast:JWST/product/jw01410-o057_t051_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.18.0,1410,jw01410-o057_t051_nircam_clear-f200w_segm.fits,74992320,71774283,PUBLIC,3,F200W,100.246750,10.011111
1,71774283,JWST,image,jw01410-o057_t051_nircam_clear-f200w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01410-o057_t051_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.18.0,1410,jw01410-o057_t051_nircam_clear-f200w_i2d.fits,524750400,71774283,PUBLIC,3,F200W,100.246750,10.011111
2,83336318,JWST,image,jw01089-o001_t001_nircam_clear-f200w,target (L3) : segmentation map,D,mast:JWST/product/jw01089-o001_t001_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.19.1,1089,jw01089-o001_t001_nircam_clear-f200w_segm.fits,87831360,83336318,PUBLIC,3,F200W,254.713084,34.314610
3,83336318,JWST,image,jw01089-o001_t001_nircam_clear-f200w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01089-o001_t001_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.19.1,1089,jw01089-o001_t001_nircam_clear-f200w_i2d.fits,966170880,83336318,PUBLIC,3,F200W,254.713084,34.314610
4,94653084,JWST,image,jw01840-o010_t003_nircam_clear-f200w,target (L3) : segmentation map,D,mast:JWST/product/jw01840-o010_t003_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.19.1,1840,jw01840-o010_t003_nircam_clear-f200w_segm.fits,82082880,94653084,PUBLIC,3,F200W,342.190833,-44.537478
5,94653084,JWST,image,jw01840-o010_t003_nircam_clear-f200w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01840-o010_t003_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.19.1,1840,jw01840-o010_t003_nircam_clear-f200w_i2d.fits,574407360,94653084,PUBLIC,3,F200W,342.190833,-44.537478
6,106620592,JWST,image,jw01345-o061_t043_nircam_clear-f200w,target (L3) : segmentation map,D,mast:JWST/product/jw01345-o061_t043_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.19.2,1345,jw01345-o061_t043_nircam_clear-f200w_segm.fits,174081600,106620592,PUBLIC,3,F200W,214.855738,52.855594
7,106620592,JWST,image,jw01345-o061_t043_nircam_clear-f200w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01345-o061_t043_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.19.2,1345,jw01345-o061_t043_nircam_clear-f200w_i2d.fits,1218424320,106620592,PUBLIC,3,F200W,214.855738,52.855594
8,127234708,JWST,image,jw01181-c1001_t008_nircam_clear-f200w,target (L3) : segmentation map,D,mast:JWST/product/jw01181-c1001_t008_nircam_cl...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.17.1,1181,jw01181-c1001_t008_nircam_clear-f200w_segm.fits,435507840,127234708,PUBLIC,3,F200W,189.133863,62.266661
9,127234708,JWST,image,jw01181-c1001_t008_nircam_clear-f200w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01181-c1001_t008_nircam_cl...,SCIENCE,Minimum Recommended Products,I2D,...,1.17.1,1181,jw01181-c1001_t008_nircam_clear-f200w_i2d.fits,5661604800,127234708,PUBLIC,3,F200W,189.133863,62.266661

In [12]:
df_F200[["productFilename", "dataURI", "obsID", "s_ra", "s_dec"]].head()

,productFilename,dataURI,obsID,s_ra,s_dec
0,jw01410-o057_t051_nircam_clear-f200w_segm.fits,mast:JWST/product/jw01410-o057_t051_nircam_cle...,71774283,100.246750,10.011111
1,jw01410-o057_t051_nircam_clear-f200w_i2d.fits,mast:JWST/product/jw01410-o057_t051_nircam_cle...,71774283,100.246750,10.011111
2,jw01089-o001_t001_nircam_clear-f200w_segm.fits,mast:JWST/product/jw01089-o001_t001_nircam_cle...,83336318,254.713084,34.314610
3,jw01089-o001_t001_nircam_clear-f200w_i2d.fits,mast:JWST/product/jw01089-o001_t001_nircam_cle...,83336318,254.713084,34.314610
4,jw01840-o010_t003_nircam_clear-f200w_segm.fits,mast:JWST/product/jw01840-o010_t003_nircam_cle...,94653084,342.190833,-44.537478

In [13]:
df_F277.head(10)

,obsID,obs_collection,dataproduct_type,obs_id,description,type,dataURI,productType,productGroupDescription,productSubGroupDescription,...,prvversion,proposal_id,productFilename,size,parent_obsid,dataRights,calib_level,filters,s_ra,s_dec
0,71644586,JWST,image,jw01057-o004_t001_nircam_clear-f277w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01057-o004_t001_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1057,jw01057-o004_t001_nircam_clear-f277w_i2d.fits,285966720,71644586,PUBLIC,3,F277W,79.656667,-69.407139
1,71751662,JWST,image,jw01160-o022_t011_nircam_clear-f277w,target (L3) : segmentation map,D,mast:JWST/product/jw01160-o022_t011_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1160,jw01160-o022_t011_nircam_clear-f277w_segm.fits,56557440,71751662,PUBLIC,3,F277W,268.918332,65.857708
2,71751662,JWST,image,jw01160-o022_t011_nircam_clear-f277w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01160-o022_t011_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1160,jw01160-o022_t011_nircam_clear-f277w_i2d.fits,395769600,71751662,PUBLIC,3,F277W,268.918332,65.857708
3,71751761,JWST,image,jw01160-o023_t013_nircam_clear-f277w-sub160,target (L3) : segmentation map,D,mast:JWST/product/jw01160-o023_t013_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1160,jw01160-o023_t013_nircam_clear-f277w-sub160_se...,161280,71751761,PUBLIC,3,F277W,269.896674,65.972542
4,71751761,JWST,image,jw01160-o023_t013_nircam_clear-f277w-sub160,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01160-o023_t013_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1160,jw01160-o023_t013_nircam_clear-f277w-sub160_i2...,964800,71751761,PUBLIC,3,F277W,269.896674,65.972542
5,71752354,JWST,image,jw01059-o307_t013_nircam_clear-f277w,target (L3) : segmentation map,D,mast:JWST/product/jw01059-o307_t013_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1059,jw01059-o307_t013_nircam_clear-f277w_segm.fits,150629760,71752354,PUBLIC,3,F277W,240.105304,-11.649622
6,71752354,JWST,image,jw01059-o307_t013_nircam_clear-f277w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01059-o307_t013_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1059,jw01059-o307_t013_nircam_clear-f277w_i2d.fits,1054275840,71752354,PUBLIC,3,F277W,240.105304,-11.649622
7,75021474,JWST,image,jw01067-o301_t010_nircam_clear-f277w,target (L3) : segmentation map,D,mast:JWST/product/jw01067-o301_t010_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.19.1,1067,jw01067-o301_t010_nircam_clear-f277w_segm.fits,17614080,75021474,PUBLIC,3,F277W,241.360895,29.699431
8,75021474,JWST,image,jw01067-o301_t010_nircam_clear-f277w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01067-o301_t010_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.19.1,1067,jw01067-o301_t010_nircam_clear-f277w_i2d.fits,123105600,75021474,PUBLIC,3,F277W,241.360895,29.699431
9,79237245,JWST,image,jw01063-o118_t004_nircam_f277w-maskbar,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01063-o118_t004_nircam_f27...,SCIENCE,Minimum Recommended Products,I2D,...,1.9.6,1063,jw01063-o118_t004_nircam_f277w-maskbar_i2d.fits,1233607680,79237245,PUBLIC,3,F277W;MASKBAR,106.908500,27.563086

In [14]:
df_F277[["productFilename", "dataURI", "obsID", "s_ra", "s_dec"]].head()

,productFilename,dataURI,obsID,s_ra,s_dec
0,jw01057-o004_t001_nircam_clear-f277w_i2d.fits,mast:JWST/product/jw01057-o004_t001_nircam_cle...,71644586,79.656667,-69.407139
1,jw01160-o022_t011_nircam_clear-f277w_segm.fits,mast:JWST/product/jw01160-o022_t011_nircam_cle...,71751662,268.918332,65.857708
2,jw01160-o022_t011_nircam_clear-f277w_i2d.fits,mast:JWST/product/jw01160-o022_t011_nircam_cle...,71751662,268.918332,65.857708
3,jw01160-o023_t013_nircam_clear-f277w-sub160_se...,mast:JWST/product/jw01160-o023_t013_nircam_cle...,71751761,269.896674,65.972542
4,jw01160-o023_t013_nircam_clear-f277w-sub160_i2...,mast:JWST/product/jw01160-o023_t013_nircam_cle...,71751761,269.896674,65.972542

In [15]:
df_F444.head(10)

,obsID,obs_collection,dataproduct_type,obs_id,description,type,dataURI,productType,productGroupDescription,productSubGroupDescription,...,prvversion,proposal_id,productFilename,size,parent_obsid,dataRights,calib_level,filters,s_ra,s_dec
0,71644585,JWST,image,jw01057-o004_t001_nircam_clear-f444w,target (L3) : segmentation map,D,mast:JWST/product/jw01057-o004_t001_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1057,jw01057-o004_t001_nircam_clear-f444w_segm.fits,40849920,71644585,PUBLIC,3,F444W,79.656667,-69.407139
1,71644585,JWST,image,jw01057-o004_t001_nircam_clear-f444w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01057-o004_t001_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1057,jw01057-o004_t001_nircam_clear-f444w_i2d.fits,285785280,71644585,PUBLIC,3,F444W,79.656667,-69.407139
2,71649557,JWST,image,jw01409-o031_t014_nircam_f444w-f470n,target (L3) : segmentation map,D,mast:JWST/product/jw01409-o031_t014_nircam_f44...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1409,jw01409-o031_t014_nircam_f444w-f470n_segm.fits,17216640,71649557,PUBLIC,3,F444W;F470N,146.842716,63.241905
3,71649557,JWST,image,jw01409-o031_t014_nircam_f444w-f470n,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01409-o031_t014_nircam_f44...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1409,jw01409-o031_t014_nircam_f444w-f470n_i2d.fits,120329280,71649557,PUBLIC,3,F444W;F470N,146.842716,63.241905
4,71650838,JWST,image,jw01409-o028_t015_nircam_f444w-f470n,target (L3) : segmentation map,D,mast:JWST/product/jw01409-o028_t015_nircam_f44...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1409,jw01409-o028_t015_nircam_f444w-f470n_segm.fits,17216640,71650838,PUBLIC,3,F444W;F470N,146.842716,63.241905
5,71650838,JWST,image,jw01409-o028_t015_nircam_f444w-f470n,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01409-o028_t015_nircam_f44...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1409,jw01409-o028_t015_nircam_f444w-f470n_i2d.fits,120329280,71650838,PUBLIC,3,F444W;F470N,146.842716,63.241905
6,71672219,JWST,image,jw01409-o128_t015_nircam_f444w-f470n,target (L3) : segmentation map,D,mast:JWST/product/jw01409-o128_t015_nircam_f44...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1409,jw01409-o128_t015_nircam_f444w-f470n_segm.fits,17213760,71672219,PUBLIC,3,F444W;F470N,146.842716,63.241905
7,71672219,JWST,image,jw01409-o128_t015_nircam_f444w-f470n,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01409-o128_t015_nircam_f44...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1409,jw01409-o128_t015_nircam_f444w-f470n_i2d.fits,120329280,71672219,PUBLIC,3,F444W;F470N,146.842716,63.241905
8,71735399,JWST,image,jw01409-o129_t016_nircam_clear-f444w,target (L3) : segmentation map,D,mast:JWST/product/jw01409-o129_t016_nircam_cle...,AUXILIARY,Minimum Recommended Products,SEGM,...,1.10.1,1409,jw01409-o129_t016_nircam_clear-f444w_segm.fits,17213760,71735399,PUBLIC,3,F444W,159.341103,-69.665642
9,71735399,JWST,image,jw01409-o129_t016_nircam_clear-f444w,exposure/target (L2b/L3): rectified 2D image,D,mast:JWST/product/jw01409-o129_t016_nircam_cle...,SCIENCE,Minimum Recommended Products,I2D,...,1.10.1,1409,jw01409-o129_t016_nircam_clear-f444w_i2d.fits,120326400,71735399,PUBLIC,3,F444W,159.341103,-69.665642

In [16]:
df_F444[["productFilename", "dataURI", "obsID", "s_ra", "s_dec"]].head()

,productFilename,dataURI,obsID,s_ra,s_dec
0,jw01057-o004_t001_nircam_clear-f444w_segm.fits,mast:JWST/product/jw01057-o004_t001_nircam_cle...,71644585,79.656667,-69.407139
1,jw01057-o004_t001_nircam_clear-f444w_i2d.fits,mast:JWST/product/jw01057-o004_t001_nircam_cle...,71644585,79.656667,-69.407139
2,jw01409-o031_t014_nircam_f444w-f470n_segm.fits,mast:JWST/product/jw01409-o031_t014_nircam_f44...,71649557,146.842716,63.241905
3,jw01409-o031_t014_nircam_f444w-f470n_i2d.fits,mast:JWST/product/jw01409-o031_t014_nircam_f44...,71649557,146.842716,63.241905
4,jw01409-o028_t015_nircam_f444w-f470n_segm.fits,mast:JWST/product/jw01409-o028_t015_nircam_f44...,71650838,146.842716,63.241905